### PR TITLE
BoardConfigCommon: make all paths for toolchains use shell pwd instea…

### PR DESCRIPTION
**Pull request by FacuM**
…d of ANDROID_BUILD_TOP.

As you stated @Akianonymus.

### CODE REVIEW

**Comment by Akianonymus** [comment]
aah , thx , i missed this

**Comment by FacuM** [comment]
Glad I could help a bit at least :3.

**Comment by FacuM** [comment]
Brain crash, nvm.

**Comment by Akianonymus** [comment]
I force pushed and fixed this

**Pull request closed without merging**
